### ISSUE TITLE
Create a container/VM

### ISSUE THREAD

**Issue by stanisic** [schnorr/starvz#3]
Similar motivation as Issue #1, only it would make it even easier for the users (especially the ones not so fluent with R) to install and use starvz.

**Comment by schnorr** [comment]
Perhaps @guilhermealles can bring his knowledge about singularity on this matter.

**Comment by guilhermealles** [comment]
Considering that the most common use case for StarVZ is in a personal computer and not in a shared environment like a cluster (maybe I am wrong in this aspect, more on that later), I would advise against Singularity containers. Instead, Docker containers might be the best alternative because it is much more likely that the end user will understand how to pull, build and spin them up.

Now, if users want to run StarVZ in a cluster (which is very likely to **not** have Docker available), then Singularity may come to the rescue. Even so, we can build a Singularity image by pointing it to an existing Dockerfile, so the first step can still be creating a Docker container for StarVZ.

**Comment by stanisic** [comment]
I am not an expert on this topic, but just to note that many clusters do not support Singularity either, due to the potential security issues. 

Considering StarVZ used mostly on personal computers, it is certainly true for the small use cases, as it is the most convenient. However, for larger traces one would need an access to a machine with a much larger memory, typically available in clusters...

Anyway, starting with a Docker image sounds like a good choice...

**Comment by schnorr** [comment]
Thanks to @guilhermealles know-how, we were able to create a `docker` container to facilitate the utilization. Please check [this note regarding container pull and use](https://github.com/schnorr/starvz#docker-container).
